name: yunhwan-portfolio-image-build

on:
  push:
    branches: ["main"]
    paths-ignore:
      - '.github/**'
      - '*.md'
concurrency:  #작업 중복 실행 방지
  group: docker-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Set datetime
        id: date
        run: echo "datetime=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Source download on Github
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_ID }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push (latest)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: | 
            docker.io/${{ secrets.DOCKER_HUB_REGISTRY }}/${{secrets.DOCKER_HUB_REPOSITORY}}:latest
            docker.io/${{ secrets.DOCKER_HUB_REGISTRY }}/${{secrets.DOCKER_HUB_REPOSITORY}}:${{ steps.date.outputs.datetime }}

      - name: Deploy On AWS EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker login -u ${{ secrets.DOCKER_HUB_ID }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
            
            # 기존 컨테이너 중지 및 삭제
            sudo docker stop yh-portfolio || true
            sudo docker rm yh-portfolio || true
            
            #이전 이미지 제거
            sudo docker image prune -af
            
            # 최신 이미지 Pull
            sudo docker pull ${{ secrets.DOCKER_HUB_REGISTRY }}/${{secrets.DOCKER_HUB_REPOSITORY}}:latest
            
            # 새 컨테이너 실행
            sudo docker run -d \
              --name yh-portfolio \
              -p 3000:3000 \
              ${{ secrets.DOCKER_HUB_REGISTRY }}/${{secrets.DOCKER_HUB_REPOSITORY}}:latest